### ISSUE TITLE
SIGTRAP -[LJPhone initWithMultiValue:index:] (LJPerson.m:)

### ISSUE THREAD

**Issue by free1990** [leejayID/LJContactManager#10]
0	CoreFoundation
CFRelease + 1084
1	testApp
-[LJPhone initWithMultiValue:index:] (LJPerson.m:346)
2	testApp
-[LJPhone initWithMultiValue:index:] (LJPerson.m:346)
3	testApp
-[LJPerson initWithRecord:] (LJPerson.m:219)
4	superman
__63-[LJContactManager _asynAccessAddressBookWithSort:completcion:]_block_invoke (LJContactManager.m:407)
5	libdispatch.dylib
__dispatch_call_block_and_release + 24
6	libdispatch.dylib
__dispatch_client_callout + 16
7	libdispatch.dylib
__dispatch_root_queue_drain + 1152
8	libdispatch.dylib
__dispatch_worker_thread3 + 108
9	libsystem_pthread.dylib
_pthread_wqthread + 816

**Comment by leejayID** [comment]
你好，你反馈的问题，已经在新版本中解决。
