### ISSUE TITLE
手机号码格式问题

### ISSUE THREAD

**Issue by 815807765** [leejayID/LJContactManager#14]
我选择联系人时候有的有空格（188 888 888 88）这种，有的就没有空格（18888888888），请问这个是什么原因啊，我选择时候看了在手机通讯录显示的都是有空格的。

**Comment by leejayID** [comment]
```objc
- (NSString *)filterSpecialString:(NSString *)string
{
    if (string == nil)
    {
        return @"";
    }
    
    string = [string stringByReplacingOccurrencesOfString:@"+86" withString:@""];
    string = [string stringByReplacingOccurrencesOfString:@"-" withString:@""];
    string = [string stringByReplacingOccurrencesOfString:@"(" withString:@""];
    string = [string stringByReplacingOccurrencesOfString:@")" withString:@""];
    string = [string stringByReplacingOccurrencesOfString:@" " withString:@""];
    string = [string stringByReplacingOccurrencesOfString:@" " withString:@""];
    return string;
}
```
你先用这个方法在回调里面过滤一下

**Comment by leejayID** [comment]
后面我会发一个新版，新版中会增加过滤的方法，不用手动去过滤，如果比较急，可以先手动加入一下上面的方法

**Comment by leejayID** [comment]
新版已发，你可以更新 cocoapods 1.0.4版本，或者直接下载新的代码替换

**Comment by 815807765** [comment]
你好，当时看到这个问题，我自己在回调里面加了去空字符串的处理（就是你上面代码中的方法），但是还是会出现空格的问题，后来我在会掉里面用这个方法可以去掉空格    NSString *cleaned = [[phonenum componentsSeparatedByCharactersInSet:[NSCharacterSet whitespaceCharacterSet]] componentsJoinedByString:@""]，请问你自己测试过没有，我这边用[stringByReplacingOccurrencesOfString:@" " withString:@""]这个方法好像不起作用

**Comment by leejayID** [comment]
你下载最新的版本替换一下，我已经做了处理
