### ISSUE TITLE
组内排序的修复Cocoapods尚未更新

### ISSUE THREAD

**Issue by SunnyWjw** [leejayID/LJContactManager#16]
你好，我刚才搜索了下，Cocoapods尚未更新

**Comment by leejayID** [comment]
已经更新了，你先把本地的缓存清一下。




| |
李健
邮箱：leejay_email@163.com
|

签名由 网易邮箱大师 定制

在2018年09月11日 12:42，SunnyWu 写道：

你好，我刚才搜索了下，Cocoapods尚未更新

**Comment by SunnyWjw** [comment]
我本地已清除pod缓存，但通过 pod search 搜索，任搜索到的版本是1.0.5，但是我看到你的最新的提交记录中已经修改了版本记录。不知道这是为何

**Comment by leejayID** [comment]
我刚刚试了下，可以啊，你试试 pod update
![image.png](https://upload-images.jianshu.io/upload_images/1321491-f3f94e175a88bc61.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
