### ISSUE TITLE
iOS7支持么？

### ISSUE THREAD

**Issue by sophyphilo** [leejayID/LJContactManager#5]

**Comment by leejayID** [comment]
没有对 iOS 7 做适配

**Comment by xuchuang** [comment]
没有适配是说里面有方法在iOS 7不能用吗？因为我们要适配iOS 7，所以我不知道我直接把你的代码拖进项目在iOS 7会不会crash，现在7.0的系统的手机还是很难找的，所以请你能告诉我一下好嘛，谢谢了大神。

**Comment by leejayID** [comment]
@xuchuang 现在很少有支持 iOS 7 的，拖进去可能没有效果，应该不会崩溃

**Comment by xuchuang** [comment]
好的，非常谢谢了
