### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by VermouthC** [leejayID/LJContactManager#8]
你的这个通讯录的库封装的很好了,阅读你的代码很赞! 
有一点建议是 添加到已存在的联系人和 创建新的联系人两个接口 操作完成后,需要知道操作的结果成功还是失败,如果添加结果的回调,会更好一点,仅仅个人建议,不喜请忽略(Close).

**Comment by leejayID** [comment]
谢谢你的建议，后期我会增加
